<?php
return array(
    'components'=>array(

        'widgets'=>array(
            'class'=>'PDObjectLocator',
            'objectFactoryId'=>'PDWidgetFactory',
            'objects'=>array(
                'layout2Column'=>array(
                    'class'=>'page.widgets.PDPageLayout2Column',
                    'params'=>array(
                        'view'=>'page/_/layout/2column',
                        'htmlBlockId'=>'page/widgets/html'
                    ),
                ),
                'layout1Column'=>array(
                    'class'=>'PDLayoutWidget',
                    'params'=>array(
                        'view'=>'page/_/layout/1column',
                        'htmlBlockId'=>'page/widgets/html'
                    ),
                ),
                'html'=>array(
                    'class'=>'PDWidget',
                    'params'=>array(
                        'view'=>'page/_/html',
                        'children'=>array(
                            'head'=>'page/widgets/head',
                            'body'=>'page/widgets/body'
                        ),
                    )
                ),
                'head'=>array(
                    'class'=>'page.widgets.PDPageHeadWidget',
                    'params'=>array('view'=>'page/_/head')
                ),
                'body'=>array(
                    'class'=>'PDWidget',
                    'params'=>array('view'=>'page/_/body')
                ),
                'notification'=>array(
                    'class'=>'PDWidget',
                    'params'=>array('view'=>'page/_/notification')
                ),
                'header'=>array(
                    'class'=>'PDWidget',
                    'params'=>array('view'=>'page/_/header')
                ),
                'footer'=>array(
                    'class'=>'PDWidget',
                    'params'=>array('view'=>'page/_/footer')
                ),
                'modal'=>array(
                    'class'=>'PDWidget',
                    'params'=>array('view'=>'page/_/modal')
                )
            ),
        )
    )
);